import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import CoinContextProvider from "@/context/CoinContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Place",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
       
      <body className={inter.className}>
      <CoinContextProvider>
      <Navbar />
        {children}
        <Footer/>
      </CoinContextProvider>
      </body>
    </html>
  );
}
